# CONTRAIL SECURITY

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT JUNIPER.NET
# Copyright (c) 2017 Juniper Networks, Inc. All rights reserved

heat_template_version: 2015-10-15

description: >
  HOT template to create a Tag:

parameters:
  application1_tag_name:
    type: string
    description: name for the Tag
  application1_tag_value:
    type: string
    description: Tag Value
  application1_tagAnnotation_key:
    type: string
    description: key for the Tag
  application1_tagAnnotation_value:
    type: string
    description: value for the Tag
  application1_tag_type:
    type: string
    description: Tag type

  deployment1_tag_name:
    type: string
    description: name for the Tag
  deployment1_tag_value:
    type: string
    description: Tag Value
  deployment1_tagAnnotation_key:
    type: string
    description: key for the Tag
  deployment1_tagAnnotation_value:
    type: string
    description: value for the Tag
  deployment1_tag_type:
    type: string
    description: Tag type

  deployment2_tag_name:
    type: string
    description: name for the Tag
  deployment2_tag_value:
    type: string
    description: Tag Value
  deployment2_tagAnnotation_key:
    type: string
    description: key for the Tag
  deployment2_tagAnnotation_value:
    type: string
    description: value for the Tag
  deployment2_tag_type:
    type: string
    description: Tag type

  site1_tag_name:
    type: string
    description: name for the Tag
  site1_tag_value:
    type: string
    description: Tag Value
  site1_tagAnnotation_key:
    type: string
    description: key for the Tag
  site1_tagAnnotation_value:
    type: string
    description: value for the Tag
  site1_tag_type:
    type: string
    description: Tag type
    
  site2_tag_name:
    type: string
    description: name for the Tag
  site2_tag_value:
    type: string
    description: Tag Value
  site2_tagAnnotation_key:
    type: string
    description: key for the Tag
  site2_tagAnnotation_value:
    type: string
    description: value for the Tag
  site2_tag_type:
    type: string
    description: Tag type

  tier1_tag_name:
    type: string
    description: name for the Tag
  tier1_tag_value:
    type: string
    description: Tag Value
  tier1_tagAnnotation_key:
    type: string
    description: key for the Tag
  tier1_tagAnnotation_value:
    type: string
    description: value for the Tag
  tier1_tag_type:
    type: string
    description: Tag type

  tier2_tag_name:
    type: string
    description: name for the Tag
  tier2_tag_value:
    type: string
    description: Tag Value
  tier2_tagAnnotation_key:
    type: string
    description: key for the Tag
  tier2_tagAnnotation_value:
    type: string
    description: value for the Tag
  tier2_tag_type:
    type: string
    description: Tag type

  tier3_tag_name:
    type: string
    description: name for the Tag
  tier3_tag_value:
    type: string
    description: Tag Value
  tier3_tagAnnotation_key:
    type: string
    description: key for the Tag
  tier3_tagAnnotation_value:
    type: string
    description: value for the Tag
  tier3_tag_type:
    type: string
    description: Tag type

resources:
  application1_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: application1_tag_name }
      display_name: { get_param: application1_tag_name }
      tag_value: { get_param: application1_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: application1_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: application1_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: application1_tag_type }

  deployment1_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: deployment1_tag_name }
      display_name: { get_param: deployment1_tag_name }
      tag_value: { get_param: deployment1_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: deployment1_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: deployment1_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: deployment1_tag_type }

  deployment2_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: deployment2_tag_name }
      display_name: { get_param: deployment2_tag_name }
      tag_value: { get_param: deployment2_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: deployment2_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: deployment2_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: deployment2_tag_type }

  site1_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: site1_tag_name }
      display_name: { get_param: site1_tag_name }
      tag_value: { get_param: site1_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: site1_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: site1_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: site1_tag_type }

  site2_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: site2_tag_name }
      display_name: { get_param: site2_tag_name }
      tag_value: { get_param: site2_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: site2_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: site2_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: site2_tag_type }

  tier1_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: tier1_tag_name }
      display_name: { get_param: tier1_tag_name }
      tag_value: { get_param: tier1_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: tier1_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: tier1_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: tier1_tag_type }

  tier2_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: tier2_tag_name }
      display_name: { get_param: tier2_tag_name }
      tag_value: { get_param: tier2_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: tier2_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: tier2_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: tier2_tag_type }

  tier3_template_Tag:
    type: OS::ContrailV2::Tag
    properties:
      name: { get_param: tier3_tag_name }
      display_name: { get_param: tier3_tag_name }
      tag_value: { get_param: tier3_tag_value }
      annotations:
        {
          annotations_key_value_pair:
            [{
              annotations_key_value_pair_key: { get_param: tier3_tagAnnotation_key },
              annotations_key_value_pair_value: { get_param: tier3_tagAnnotation_value },
            }],
        }
      tag_type: { get_param: tier3_tag_type }
